### ISSUE TITLE
Language feature: `bytes` type

### ISSUE THREAD

**Issue by tusharsadhwani** [tusharsadhwani/interpreted#14]
Currently, strings are supported but bytes are not. Adding a bytes type would mean:

- Tokenizing strings with a `b` prefix
- Implementing operators (`+`, `*` and `[]`) for bytes.

```python
a = b'abc'
print(a)         # b'abc'
print(a[0])      # 97
print(a * 2)     # b'abcabc'
print(a + b'd')  # b'abcd'
```

**Comment by amangupta201** [comment]
We can do it like this:
1) Defining a bytes variable:

a = b'abc'
Printing the bytes variable:

2) print(a)  # Output: b'abc'
Accessing bytes using indexing:


3) print(a[0])  # Output: 97
Replicating bytes with the * operator:


4) print(a * 2)  # Output: b'abcabc'
Concatenating bytes with the + operator:


5) print(a + b'd')  # Output: b'abcd'

**Comment by tusharsadhwani** [comment]
@amangupta201 Would you like to work on implementing this in yhe interpreter?

**Comment by amangupta201** [comment]
> 

Yes
